server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      connectionProperties: config.decrypt=false;
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update  # 自动建表（开发用）: none, validate, update, create, create-drop
#    show-sql: true       # 打印SQL语句
#    properties:
#      hibernate:
#        format_sql: true # 格式化SQL
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.subject.infra.basic.entity
  configuration:
    log-impl: org.apache.ibatis.logging.std out.StdOutImpl